In [11]:
import torch

In [12]:
import torch.nn as nn

In [13]:
BATCH_SIZE = 32
IMAGE_SIZE = 256
CHANNELS=3
EPOCHS=50

In [14]:
from torchvision import datasets, transforms
# Define transformations
data_transforms = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
])

# Load the dataset
dataset = datasets.ImageFolder(
    root="PlantVillage",
    transform=data_transforms
)

# Create DataLoader for batching and shuffling
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4  # You can adjust this based on your system
)

In [15]:
for image_batch, labels_batch in data_loader:
    print(image_batch.shape)  # Shape of the image batch
    print(labels_batch.numpy())  # Convert labels tensor to NumPy array
    #sab images ko mix kr dia ferr 32 32 images ka batch bnaa dia  usme us leaf k hisaab se label kr dia 0 for early blight ...

torch.Size([32, 3, 256, 256])
[1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1 2 1 0 1]
torch.Size([32, 3, 256, 256])
[0 1 1 0 2 0 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0]
torch.Size([32, 3, 256, 256])
[0 1 1 1 0 0 0 0 1 1 1 2 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0]
torch.Size([32, 3, 256, 256])
[0 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 1 1 2 1 1 1 1 1 0 0 0 0 0 0 1]
torch.Size([32, 3, 256, 256])
[0 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1]
torch.Size([32, 3, 256, 256])
[0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 2 1 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0]
torch.Size([32, 3, 256, 256])
[0 1 0 0 0 1 1 1 0 2 1 0 0 1 0 1 1 1 1 0 0 1 1 1 2 1 2 1 0 0 1 1]
torch.Size([32, 3, 256, 256])
[1 0 0 1 0 2 1 2 1 0 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1]
torch.Size([32, 3, 256, 256])
[1 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 1 2 0 1 0 1 1 1]
torch.Size([32, 3, 256, 256])
[2 1 0 1 1 0 0 1 1 2 0 1 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 2 1 0 1 1]
torch.Size([32, 3, 256, 256])
[0 0 1 0 0

In [16]:
import os
data_dir = "PlantVillage"
class_names = sorted(os.listdir(data_dir))
print(class_names)


['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']


In [17]:
import matplotlib as plt

In [18]:
for image_batch, labels_batch in data_loader:
    # Create a figure with a 3x4 grid of subplots
    plt.figure(figsize=(10, 10))
    for i in range(min(len(image_batch), 12)):  # Limiting to the first 12 images
        # Plot the image
        ax = plt.subplot(3, 4, i + 1)
        plt.imshow(np.transpose(image_batch[i], (1, 2, 0)))  # Transpose the image tensor to (H, W, C) for plotting
        plt.title(class_names[labels_batch[i].item()])
        plt.axis("off")
    plt.show()
    break 

AttributeError: module 'matplotlib' has no attribute 'figure'

In [ ]:
num_samples = 54
train_ds = torch.utils.data.Subset(dataset, range(num_samples))

In [ ]:
num_samples_validation = 6
val_ds = torch.utils.data.Subset(test_ds, range(num_samples_validation))

In [ ]:
start_index = 54
test_ds = torch.utils.data.Subset(dataset, range(start_index, len(dataset)))


In [ ]:
num_samples_validation = 6
test_ds = torch.utils.data.Subset(test_ds, range(num_samples_validation, len(test_ds)))


In [ ]:
from torch.utils.data import DataLoader, random_split

def get_dataset_partitions_pytorch(dataset, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    
    dataset_size = len(dataset)
    
    if shuffle:
        # Create indices for shuffling
        indices = torch.randperm(dataset_size)
        # Shuffle the dataset based on indices
        dataset = torch.utils.data.Subset(dataset, indices)
    
    train_size = int(train_split * dataset_size)
    val_size = int(val_split * dataset_size)
    test_size = dataset_size - train_size - val_size
    
    # Split the dataset
    train_dataset, val_dataset, test_dataset = torch.utils.data.random_split(
        dataset, [train_size, val_size, test_size]
    )
    
    return train_dataset, val_dataset, test_dataset

# Usage example:
# Assuming 'dataset' is your PyTorch dataset
train_dataset, val_dataset, test_dataset = get_dataset_partitions_pytorch(dataset)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE)


In [ ]:
from torch.utils.data import DataLoader

# Assuming you have already created train_ds, val_ds, and test_ds

# Define batch sizes
batch_size = 64

# Create DataLoader instances for train, val, and test datasets
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=4)
val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=True, num_workers=4)
test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=True, num_workers=4)

In [19]:
import torchvision.transforms as transforms

# Define the desired image size
IMAGE_SIZE = 224  # Example size, replace with your desired size

# Define the sequence of transforms
resize_and_rescale = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.0, 0.0, 0.0], std=[1.0/255.0, 1.0/255.0, 1.0/255.0])
])


In [20]:
import torch
import torch.nn as nn

class CNNModel(nn.Module):
    def __init__(self, n_classes):
        super(CNNModel, self).__init__()
        self.conv_layers = nn.Sequential(
            nn.Conv2d(in_channels=CHANNELS, out_channels=32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * (IMAGE_SIZE // 64) ** 2, 64),
            nn.ReLU(),
            nn.Linear(64, n_classes),
            nn.Softmax(dim=1)
        )

    def forward(self, x):
        x = self.conv_layers(x)
        x = self.fc_layers(x)
        return x

# Create an instance of the model
model = CNNModel(n_classes)

# Print model summary
print(model)


NameError: name 'n_classes' is not defined

In [ ]:
print(model)

In [ ]:
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# Assuming you have already created train_ds as a PyTorch dataset

# Define the sequence of data augmentation transforms for training
data_augmentation = transforms.Compose([
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=20),
])

# Create a DataLoader for the training dataset with data augmentation
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)

# Apply data augmentation dynamically during training
augmented_train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
for batch in augmented_train_loader:
    images, labels = batch
    images_augmented = torch.stack([data_augmentation(image) for image in images])
    # Train your model using images_augmented and labels


In [ ]:
# Assuming 'train_dataset' is your PyTorch dataset
# Define data augmentation transforms
data_augmentation = transforms.Compose([
    transforms.RandomHorizontalFlip(p=0.5),  # Randomly flip the image horizontally with probability 0.5
    transforms.RandomVerticalFlip(p=0.5),    # Randomly flip the image vertically with probability 0.5
    transforms.RandomRotation(degrees=20),    # Randomly rotate the image by a maximum of 20 degrees
])

# Define a custom dataset class to apply data augmentation
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, transform=None):
        self.dataset = dataset
        self.transform = transform

    def __getitem__(self, index):
        image, label = self.dataset[index]
        if self.transform:
            image = self.transform(image)
        return image, label

    def __len__(self):
        return len(self.dataset)

# Apply data augmentation to the training dataset
train_dataset_augmented = CustomDataset(train_dataset, transform=data_augmentation)

# Create a DataLoader with prefetching
train_loader = DataLoader(
    train_dataset_augmented,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4,  # You can adjust this based on your system
    pin_memory=True
)


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

# Assuming you have defined your model and datasets
# Define optimizer
optimizer = optim.Adam(model.parameters())

# Define loss function
criterion = nn.CrossEntropyLoss()

# Define the number of epochs
epochs = 5

# Training loop
for epoch in range(epochs):
    # Training
    model.train()
    train_loss = 0.0
    correct_train = 0
    total_train = 0
    for inputs, targets in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item() * inputs.size(0)
        _, predicted = outputs.max(1)
        correct_train += predicted.eq(targets).sum().item()
        total_train += targets.size(0)
        
    train_loss = train_loss / len(train_loader.dataset)
    train_accuracy = correct_train / total_train
    
    # Validation
    model.eval()
    val_loss = 0.0
    correct_val = 0
    total_val = 0
    with torch.no_grad():
        for inputs, targets in val_loader:
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            
            val_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
 


In [ ]:
import torch

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Set the model to evaluation mode and move it to the device
model.eval()
model.to(device)

total_correct = 0
total_samples = 0
with torch.no_grad():
    for inputs, targets in test_loader:
        # Move inputs and targets to the device
        inputs = inputs.to(device)
        targets = targets.to(device)
        
        # Forward pass
        outputs = model(inputs)
        
        # Get predictions
        _, predicted = outputs.max(1)
        
        # Update total correct and total samples
        total_correct += predicted.eq(targets).sum().item()
        total_samples += targets.size(0)

# Calculate accuracy
accuracy = total_correct / total_samples
print(f'Test Accuracy: {accuracy:.4f}')


In [ ]:
#scores
# Set the model to evaluation mode and move it to the device
model.eval()
model.to(device)

# List to store the predicted scores
all_scores = []

with torch.no_grad():
    for inputs, _ in test_loader:
        # Move inputs to the device
        inputs = inputs.to(device)
        
        # Forward pass
        outputs = model(inputs)
        
        # Append the predicted scores
        all_scores.append(outputs.cpu().numpy())  # Convert to numpy array and move to CPU

# Concatenate the scores from all batches
scores = np.concatenate(all_scores)

# Now 'scores' contains the predicted scores for each class for each sample in the test dataset
